### ISSUE TITLE
Does not run in dockerimage 

### ISSUE THREAD

**Issue by jniclas** [orca-build/orca#1]
Hey,

tried to run `php orca.phar --directory=.` in the dockerimage webdevops/php-apache-dev:7.4 (https://registry.hub.docker.com/r/webdevops/php-apache-dev) without volumes.
Before that, I installed ORCA inside the container with 
```
cd ~
git clone https://github.com/dockware/dockware.git
cd dockware
curl -O https://orca-build.io/downloads/orca.zip
unzip -o orca.zip
```
But I get the error
```
PHP Warning:  include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='phar:///root/dockware/orca.phar:.:/usr/local/lib/php') in phar:///root/dockware/orca.phar/autoload.php on line 3
PHP Fatal error:  Uncaught Error: Class 'Orca\Components\CommandOptions\CommandOptions' not found in phar:///root/dockware/orca.phar/common.php:17
Stack trace:
#0 phar:///root/dockware/orca.phar/index.php(6): AppManager::run(Array)
#1 /root/dockware/orca.phar(9): include('phar:///root/do...')
#2 {main}
  thrown in phar:///root/dockware/orca.phar/common.php on line 17
make: *** [makefile:20: generate] Error 255
```
What do i miss?

best regards,
Niclas

**Comment by boxblinkracer** [comment]
hi

ähm i think a few things might be a bit mixed up here

so you should download the ZIP from the website
`curl -O https://orca-build.io/downloads/orca.zip`
`unzip -o orca.zip`
`rm -f orca.zip`

then you run this in the root directory of dockware.
`php orca.phar --directory=.` 

additionally you can just use "make install" and "make generate".


im not quite sure why you use this in a docker environment? only due to php?

the error you get sounds like missing vendors maybe because you cloned it on your own.
the steps above should work

**Comment by boxblinkracer** [comment]
ah sorry there was dockware for cloning, didnt read that

can you try the makefiles
its actually a plug and play.
clone dockware. make install and make generate...

**Comment by jniclas** [comment]
Hey,

I tried clone dockware. make install and make generate, but no success.

But I got it working with a minimal inflexible modification inside a fresh webdevops/php-apache-dev:7.4 container:
```
cd ~
git clone https://github.com/orca-build/orca.git
git clone https://github.com/dockware/dockware.git
```
Then I changed the file `~/orca/src/index.php`: 
```
3 require_once "autoload.php";
4 require_once "common.php";
```
Sadly, this didn't worked:
```
cd ~/orca
make install
...
cd src
php index.php --directory=~/dockware

  ____  _____   _____
 / __ \|  __ \ / ____|   /\
| |  | | |__) | |       /  \
| |  | |  _  /| |      / /\ \
| |__| | | \ \| |____ / ____ \
 \____/|_|  \_\_____/_/    \_\

********* ERROR *********
>> ConfigFile not found in Image pathroot
```
So I moved the target project:
```
mv ./dockware .orca/src/dockware
```
And changed also the file `~/orca/src/common.php` by setting `$absolutePath` to my fixed dockware path:
```
18 $config->load();
19
20 $rootDir = $config->getProjectDir();
21 $absolutePath = getcwd() . "/dockware";
22
23 if ($config->isShowVersion()) {
```
Now, it was possible to run
```
cd ~/orca/src
php index.php

  ____  _____   _____
 / __ \|  __ \ / ____|   /\
| |  | | |__) | |       /  \
| |  | |  _  /| |      / /\ \
| |__| | | \ \| |____ / ____ \
 \____/|_|  \_\_____/_/    \_\

>> cleaning compile directory...
>> generating images and tags...

AWESOME!
Docker files generated successfully!
```
Unfortunately I don't no what the inital problem was, looks it has something to do with the phar build and the project folder path. Maybe some of my finding can help you.

Nevertheless - I have my builds :)

Niclas

**Comment by boxblinkracer** [comment]
hi
i just saw this (sorry i forgot)
is this still a thing? it would work on different machines in our company?
maybe its gone now?

**Comment by jniclas** [comment]
Hey,

no, still not working:

```
docker run --rm -it webdevops/php-apache-dev:7.4 bash
cd ~
git clone https://github.com/dockware/dockware.git
cd dockware
make install
make generate

PHP Warning:  include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='phar:///root/dockware/orca.phar:.:/usr/local/lib/php') in phar:///root/dockware/orca.phar/autoload.php on line 3
PHP Fatal error:  Uncaught Error: Class 'Orca\Components\CommandOptions\CommandOptions' not found in phar:///root/dockware/orca.phar/common.php:17
Stack trace:
#0 phar:///root/dockware/orca.phar/index.php(6): AppManager::run(Array)
#1 /root/dockware/orca.phar(9): include('phar:///root/do...')
#2 {main}
  thrown in phar:///root/dockware/orca.phar/common.php on line 17
make: *** [makefile:23: generate] Error 255
```

But you have already extended Dockware images with the startup scripts. So I don't need ORCA at the moment. You could close the issue.

Best regards
Niclas

**Comment by boxblinkracer** [comment]
Hi

ok then I will close this ticket

I did also create a new feature thanks to your request.

if you take a look at the README then you see a new docker application.
then you have your one-liner command that creates the files for you, without having the need of orca and php stuff installed

cheers
chrisitan
